backtrack_app/backtrack_app/urls.py
from django.contrib import admin
from django.contrib.auth import  views as auth_views
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),

    # redirection to login urls
    path('', include('login.urls')),

    path('productBacklog/', include('productBacklog.urls')),
    path('projectManage/', include('projectManage.urls')),
    path('sprints/', include('sprints.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

backtrack_app/sprints/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import  url
from . import views

urlpatterns = [
    path('',views.SprintManagement, name='sprints'),
    path('pbi<int:pbi>',views.SprintBackLogsManagement.as_view(), name='sprintBacklogs'),
     url(r'^addSubtask/$',views.addSubtask, name = 'addSubtask'),
      path('createsprint',views.SprintCreate.as_view(), name='createsprints'),
      url(r'^createspri/$',views.createSprint, name = 'createSprint'),
      url(r'^managePpl/$',views.managePpl, name = 'managePpl'),
      url(r'^changesubtask/$',views.changesubtask, name = 'changesubtask'),
      url(r'^delsub/$',views.delsub, name = 'delsub'),
      url(r'^delsprint/$',views.delsprint, name = 'delsprint'),
      url(r'^changeremain/$',views.changeremain, name = 'changeremain'),
]

backtrack_app/task/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views

urlpatterns = [
    path('<int: pbi>',views.TaskManagement.as_view(), name='tasks'),
]

backtrack_app/sprints/models.py
from django.db import models
from django.contrib.auth.models import User


class ScrumMaster(models.Model):
    user = models.OneToOneField(User, related_name="ScrumMaster", on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class BurndownChart(models.Model):
    estimated_efforts = models.IntegerField()
    remaining_efforts = models.IntegerField()
    burndown_efforts = models.IntegerField()
    objects = models.Manager()

    def __str__(self):
        return f'{self.estimated_efforts} {self.remaining_efforts} {self.burndown_efforts}'


class SprintBacklog(models.Model):
    number = models.IntegerField()
    objects = models.Manager()
    information = models.CharField(max_length=200, default="Description of the current sprint")
    totalEf = models.IntegerField(default=10, null=True)
    initialEf = models.IntegerField(default=10)
    remainEf = models.IntegerField(default=10, null=True)
    id = models.AutoField(primary_key=True)
    STATUS = (('C', 'created'), ('R', 'Removed'))
    status = models.CharField(max_length=10, choices=STATUS, default='created')

    # burndown = models.OneToOneField(BurndownChart, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.number)


class Project(models.Model):
    name = models.CharField(max_length=200)
    sprintNumber = models.IntegerField(default=0)
    id = models.AutoField(primary_key=True)
    master = models.ForeignKey(ScrumMaster, on_delete=models.SET_NULL, null=True)
    sprintBacklog = models.ForeignKey(SprintBacklog, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name


class Developer(models.Model):
    user = models.OneToOneField(User, related_name="Developer", on_delete=models.CASCADE)
    isProductOwner = models.BooleanField(null=True, default=False)
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.user.username


class PBI(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, null=True, blank=True)
    description = models.CharField(max_length=200)
    id = models.AutoField(primary_key=True)
    STATUS = (('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Complete'), ('NF', 'Not Finished'))
    status = models.CharField(max_length=10, choices=STATUS, default='NS')
    sprint = models.ForeignKey(SprintBacklog, null=True, on_delete=models.SET_NULL, blank=True)
    estimated_efforts = models.IntegerField(null=True)
    remainStory = models.IntegerField(null=True, default=10)
    priority=models.IntegerField(default=0)
    objects = models.Manager()
    remaining_efforts=models.IntegerField(null=True)
    cumulative_storypoint=models.IntegerField(null=True, default=0, blank=True)

    # burndown=models.OneToOneField(BurndownChart, on_delete=models.CASCADE)
    class Meta:
        ordering = ['priority']
    def __str__(self):
        return self.description


class Task(models.Model):
    # description = models.CharField(max_length=200)
    id = models.AutoField(primary_key=True)
    # totalEf = models.IntegerField(default=10)
    # remainEf = models.IntegerField(default=10)
    pbi = models.ForeignKey(PBI, on_delete=models.CASCADE)
    objects = models.Manager()

    # burndown = models.OneToOneField(BurndownChart, on_delete=models.CASCADE)
    def __str__(self):
        return str(self.id)


class SubTask(models.Model):
    title = models.CharField(max_length=200)
    id = models.AutoField(primary_key=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, null=True)
    pbi = models.ForeignKey(PBI, on_delete=models.CASCADE, related_name="SubTask", default=0)
    initialEstimatedEffort = models.IntegerField(null=True)
    remaining_efforts = models.IntegerField(null=True)
    Developers = models.ManyToManyField(Developer)
    STATUS = (('NS', 'Not started'), ('IP', 'In progress'), ('C', 'Complete'))
    status = models.CharField(max_length=10, choices=STATUS, default='IP')

    def __str__(self):
        return self.title

class Global_Data(models.Model):
    global_id = models.CharField(max_length=20, unique=True)
    current_ID = models.CharField(max_length=20)
    cumu_point = models.DecimalField(max_digits=6, decimal_places=0)
    num_pbis = models.DecimalField(max_digits=4, decimal_places=0)

    def __str__(self):
        return self.global_id

backtrack_app/sprints/forms.py
from django import forms
from .models import PBI, SprintBacklog

class SprintForm(forms.Form):
    all_pbi=forms.ModelMultipleChoiceField(queryset=PBI.objects.all(),widget=forms.CheckboxSelectMultiple)

backtrack_app/productBacklog/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.views.generic.list import ListView
# from functools import reduce
from django.views.generic import TemplateView
from sprints.models import PBI, Developer, ScrumMaster, Project, Global_Data


# from project.models import Product_Backlog_Item
# from project.models import Global_Data

# global_data = Global_Data.objects.get(global_id='00001')
# ID = int(global_data.current_ID)
# Total_point = int(global_data.cumu_point)
# Number = int(global_data.num_pbis)

# def productBacklog(request):
#     request

def product_backlog(request):
    if request.user.is_authenticated:
        user = str(request.user)
        if request.GET.get("DeletePBI"):
            pbi = PBI.objects.get(pk=int(request.GET.get('DeletePBI')))
            priority=pbi.priority
            pbi_list=PBI.objects.order_by('priority')
            for i in range(priority,len(pbi_list)):
                pbi_list[i].priority-=1
                pbi_list[i].save()
            pbi.delete()
        if request.method =="POST":
            pbi_id=request.POST.get('pbiID',False)
            a=request.POST.get('description', False)
            b=request.POST.get('storypoint',False)
            item=PBI.objects.get(pk=int(pbi_id))
            item.description=a
            item.remainStory=b
            item.save()
        users_project = Developer.objects.filter(user__username=user)[0].project
        sprint_backlog = Project.objects.filter(name=users_project)[0].sprintBacklog
        pbis = PBI.objects.order_by('priority') # by default we show a full view of list of pbis
        for i in range(len(pbis)):
            if i==0:
                pbis[i].cumulative_storypoint=pbis[i].remainStory
                pbis[i].save()
            else:
                order=pbis[i].priority
                pbis[i].cumulative_storypoint=pbis[i].remainStory+pbis[i-1].cumulative_storypoint
                pbis[i].save()
        print(users_project)
        print(sprint_backlog)
        print(pbis)



        # print(project)
        return render(request, 'productBacklog/pbi_list.html', {'pbi_list': pbis})
        # return HttpResponse(user)

    else:
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

def addPBI(request):
        # global Total_point
        # global ID
        # global Number
        # a = str(ID)
        # a = str(ID)
        # ID = ID + 1
        b = str(request.POST.get('title',False))
        d = request.POST.get('story_point', False)
        pbis = PBI.objects.order_by('priority')
        for pbi in pbis:
            pbi.priority+=1
            pbi.save()
        PBI.objects.create(remainStory=d, description=b, priority=0, estimated_efforts=int(d/3))
        # pbis = PBI.objects.order_by('priority')
        # return render(request, 'productBacklog/pbi_list.html', {'pbi_list': pbis})
        return redirect('http://127.0.0.1:8000/productBacklog')

def upPBI(request):
        # global Total_point
        # global ID
        # global Number
        # a = str(ID)
        # a = str(ID)
        # ID = ID + 1
        priority = int(request.GET['priority'])
        if priority>0:
            current=PBI.objects.filter(priority=priority)[0]
            previous=PBI.objects.filter(priority=priority-1)[0]
            current.priority=priority-1
            previous.priority=priority
            current.save()
            previous.save()
            # PBI.objects.filter(pk=request.GET['id']).update(priority=priority-1)

        # pbis = PBI.objects.order_by('priority')
        # return render(request, 'productBacklog/pbi_list.html', {'pbi_list': pbis})
        return redirect('http://127.0.0.1:8000/productBacklog')

def downPBI(request):
        # global Total_point
        # global ID
        # global Number
        # a = str(ID)
        # a = str(ID)
        # ID = ID + 1
        priority = int(request.GET['priority'])
        # if priority != 0:
        current=PBI.objects.filter(priority=priority)[0]
        future=PBI.objects.filter(priority=priority+1)[0]
        current.priority=priority+1
        future.priority=priority
        current.save()
        future.save()
        # pbis = PBI.objects.order_by('priority')
        # return render(request, 'productBacklog/pbi_list.html', {'pbi_list': pbis})
        return redirect('http://127.0.0.1:8000/productBacklog')

# def edit(request):
#     sid = request.GET.get('sid')
#     a = str(request.GET['id_name'])
#     pbi = PBI.objects.get(id_name = a)
#     #a = pbi.id_name
#     Total_point = Total_point - int(pbi.story_point)
#     b = str(request.GET['title'])
#     c = str(request.GET['detail'])
#     d = request.GET['story_point']
#     Total_point = Total_point + int(d)
#     Global_Data.objects.filter(global_id = '00001').update(cumu_point = Total_point)
#     e = str(Total_point)
#     f = str(request.GET['status'])
#     PBI.objects.filter(id_name = a).update(
#                                   description = b, estimated_efforts = d,
#                                   status = f)
#     return render(request, 'pbi_edit.html', locals())

# class pbiViewAll(TemplateView):
#     template_name = 'productBacklog/pbi_list.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['pbi_list'] = PBI.objects.all()
#         return context
#
#     def home(request):
#         return redirect('http://127.0.0.1:8000/project/project')

    # def add(request):
    #     global Total_point
    #     global ID
    #     global Number
    #     a = str(ID)
    #     ID = ID + 1
    #     b = str(request.GET['title'])
    #     c = str(request.GET['detail'])
    #     d = request.GET['story_point']
    #     Total_point = Total_point + int(d)
    #     Number = Number + 1
    #     Global_Data.objects.filter(global_id='00001').update(current_ID=str(ID), cumu_point=Total_point,
    #                                                          num_pbis=Number)
    #     e = str(Total_point)
    #     f = str('Not Started')
    #     g = 0
    #     PBI.objects.create(
    #                                         title=b, detail=c, story_point=d,
    #                                         cumulative_story_point=e, status=f,
    #                                         priority=g)
    #     return redirect('/home/')


# def edit(request):
#     global Total_point
#     sid = request.GET.get('sid')
#     pbi = Product_Backlog_Item.objects.filter(id_name=sid).first()
#     d = Product_Backlog_Item.objects.get(id_name = sid).story_point
#     if request.method == 'POST':
#         title = request.POST.get('title')
#         detail = request.POST.get('detail')
#         story_point = request.POST.get('story_point')
#         status = request.POST.get('status')
#         Total_point = Total_point - int(d) + int(story_point)
#         Global_Data.objects.filter(global_id = '00001').update(cumu_point = Total_point)
#         Product_Backlog_Item.objects.filter(id_name=sid).update(title = title, detail = detail,
#                                                           story_point = story_point, status = status,
#                                                           cumulative_story_point = Total_point)
#         return redirect('/home/')
#     return render(request, 'pbi_edit.html', locals())
#

#
#
# # def up(request):
# #     a = str(request.GET['id_name'])
# #     pbi = Product_Backlog_Item.objects.get(id_name = a)
# #     g = pbi.priority - 1
# #     Product_Backlog_Item.objects.filter(id_name = a).update(
# #                                   priority = g)
# #     return redirect('/home/')
#
# # def down(request):
# #     a = str(request.GET['id_name'])
# #     pbi = Product_Backlog_Item.objects.get(id_name = a)
# #     g = pbi.priority + 1
# #     Product_Backlog_Item.objects.filter(id_name = a).update(
# #                                   priority = g)
# #     return redirect('/home/')
#
# def full(request):
#     return redirect('/home/')
#
class pbiViewCurrent(TemplateView):
    template_name = 'pbi_list.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['pbi_list'] = Product_Backlog_Item.objects.filter(status__in= ['Not Started', 'In Progress', 'Cancelled'])
#         return context

backtrack_app/templates/sprints/create_sprint.html
{% extends 'base.html' %}
{% block content %}
<div style="background-color:white;height: 100%;margin-left: 20px;margin-right: 120px" class="container">
<form method="POST" action="" style="margin-left: 20px">
    {%csrf_token%}
    {{form}}
    <input class="btn btn-submit pull-right" href="" type="submit" value="Choose PBIs" />
</form>
{% endblock %}

{% block script %}
{% endblock %}

{% block style %}
<style>
    #nav-bar tr td:nth-child(4) {
    background-color: lightblue;
    }
    .card {
  /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }


</style>
{% endblock %}

backtrack_app/templates/sprints/createsprint.html
{% extends 'base.html' %}
{% block content %}

<div class="panel">
        <!-- <div id="createBtn" onclick="createBtnOnclick()"><p>Create New Sprint</p></div> -->
        
        <div id="creating" style="display: block;">
            <form id="form" action="createspri/" method="post" onsubmit="formsubmit()">
                    {% csrf_token %}
            <div class="title">Create Sprint</div>

            <div id="notselected" class="thediv">
                <div class="title">Product Backlog</div>
                {% for pbi in pbi_list %}
                <div class="pbi" onclick="pbiselected(event)" id="{{pbi.id}}">{{pbi.description}}
                    <span class="initEsti circle" style="float:right;text-align: center;padding-top:3px;margin-top: 5px">
                            {{pbi.estimated_efforts }}
                    </span>
                </div>

                {%empty%}
                <div>No PBI yet.</div>
                {% endfor %}

                

            </div>

            <div class="thediv right" onload="update()">
                <input id="total" type="hidden" name="totalEf" >
                <input id="remain" type="hidden" name="remainEf" >
                <div>Total Effort Avaliable: <input id="ini" type="text" name="initialEf" value="30" onblur="update()"></div>
                <div>Accumulated Effort time of PBIs:<p id="Accumulated"> 0</p></div>
                <div>Remained Effort Time:<p id="remained"> 30</p></div>
                <input type="submit" value="Confirm" id="confirmBtn" >
            </div>
            
        </form>
        </div>
</div>
{% endblock %}

{% block script %}
<script>
        var remain =30;
        function createBtnOnclick(){
            document.getElementById("createBtn").style.display = "none";
            document.getElementById("creating").style.display = "block";
        }

        function pbiselected(ev){
            
            var cla = "selected";
            if(ev.target.classList.contains(cla)){
                ev.target.classList.remove(cla);
            }else{
                if(parseInt(ev.target.children[0].innerHTML)> remain){
                return;
            }
                ev.target.classList.add(cla);
            }
            update();
        }

        function update(){
            var selectedPBIS = document.getElementsByClassName("selected");
            var ini = parseInt(document.getElementById("ini").value);
            var acc = 0;
            for(i = 0; i < selectedPBIS.length; ++i){
                acc += parseInt(selectedPBIS[i].children[0].innerHTML);
            }

            remain = parseInt(ini) - parseInt(acc);
            document.getElementById("Accumulated").innerHTML = acc;
            document.getElementById("total").value = acc;
            document.getElementById("remained").innerHTML = remain;
            document.getElementById("remain").value = remain;



        }

        function formsubmit(){
            event.preventDefault();
            update();
            var selectedPBIS = document.getElementsByClassName("selected");
            var form = document.getElementById("form");
            for(i = 0; i < selectedPBIS.length; ++i){
                var ele = document.createElement("input");
                ele.type = "hidden";
                ele.name = "pbis[]";
                ele.value = selectedPBIS[i].id;
                form.append(ele);
            }
            form.submit();
        }

    </script>
{% endblock %}

{% block style %}
<style>
    #createBtn{
        margin-top: 255px;
        margin-left: auto;
        margin-right:auto;
        background-color:rgb(148, 73, 63);
        width: 200px;
        padding-top: 10px; 
        padding-left: 10px; 
        font-size: 20px;
        line-height: 20px;
        height: 40px;
        border: 1px solid black;
    }

    .thediv{
        float:left;
        margin-left:250px;
        width: 400px;
        height: 600px;
    }

    .right{
        margin-left:100px;
        padding-left:50px;
        padding-top:50px;
    }

    .right div{

        height: 50px;
        margin-top:15px;
        margin-bottom:15px;
    }

    .right p{
        width:20px;
    }

    #confirmBtn{
        margin-top:30px;
    }



    #nav-bar tr td:nth-child(4) {
    background-color: lightblue;
    }

    .pbi{
        width:400px;
        height:50px;
        border: 1px black solid;
        margin-left: 50px; 
        margin-top: 10px;
        margin-bottom: 20px;
        background: rgb(85, 189, 128);
    }

    

    .circle{
        height: 25px;
        width: 25px;
        background-color: #bbb;
        border-radius: 50%;
        display: inline-block;
        overflow: auto;
        margin-right:5px;
        font-style: white;
    }

    .title{
        font-weight: bold;
        font-size: 20px;
        margin-left: 50px; 
        margin-top: 10px;
        margin-bottom: 20px;
    }

    .selected{
        background: rgb(233, 76, 36);
    }

    

</style>
{% endblock %}

backtrack_app/templates/sprints/sprints.html
{% extends 'base.html' %}
{% block content %}

<div style="margin-left: 20px;margin-right: 120px; " class="container" id="currentSprint">

    <div class="row">
        <h1 style="text-align: left;margin-left: 20px;margin-top:40px">Sprint Backlog Overview</h1></div>
    <div class="row"><h2 style="text-align: left;margin: 20px" >Sprint {{sprint.number}}</h2></div>
    <div class="row" style="display: flex;">
        <div class="column" style="flex: 70%; margin-top: 10px">
            <div id="SprintInfo">
                <div style="font-size:20px;"><b >Sprint Information</b></div>
                <div id="initialEf">Available Manpower Efforts: {{sprint.initialEf}} hrs </div>
                <div >Total Estimated Efforts for Current Sprint: <span id="totalEf">{{sprint.totalEf}}</span> hrs </div>
                <!-- <div>Average Efforts for Each PBI: <span id="averageEf"></span> hrs </div> -->
                <div>Remaining Efforts: <span id="remainingEf">{{sprint.remainEf}}</span> hrs </div>
                <div>Burndown Efforts: <span id="burndownEf"></span> hrs </div>
                <form name="description_of_sprint" method="POST">
                    {%csrf_token%}
                    <p><textarea name="information_of_sprint" style="border-radius:10px;margin-left:30px; font-size: 20px" rows="10" cols="73" title="description" >{{sprint.information}}</textarea></p>
                    
                    <p style="text-align: right; padding-right: 10px; float: right;"><button style="background-color: #bbccdd;border: 1px black solid;border-radius: 5px" type="submit">SAVE</button></p>
                </form>
                <form action="delsprint/" method="POST">
                    {%csrf_token%}
                    <input type="hidden" name="sprintNumber" value={{sprint.number}}>
                    <p style="text-align: right; padding-left: 10px; float: left;"><button style="background-color: #bbccdd;border: 1px black solid;border-radius: 5px" type="submit">DELETE</button></p>
                 </form>
            </div>
        </div>
        <div class="column" style="flex: 30%;margin-top: 10px">
            {% for task in task_list %}
            <div class="card" style="margin-bottom:8px;background-color: white;box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);margin-right: 30px">
                <a href="pbi{{task.pbi.id}}">
                <div class="cardcontainer" style="padding: 2px 10px;">
                    <div style="width:100%;display: flex">
                        <div style="flex: 50%;text-align: left;margin-left: 0"><b>PBI {{task.pbi.id}}</b></div>
                        <div class="cardStatus" style="flex: 50%;">{{task.pbi.get_status_display}}</div>
                    </div>
                    <div class="description" style="width: 100%"><span><b>Description: </b></span> <span>{{task.pbi.description}}</span></div>
                    <div style="width: 100%"><span><b>Total Efforts: </b></span><span class="initialEfforts">{{task.pbi.estimated_efforts}}</span> </div>
                    <div style="width: 100%"><span><b>Remaining Efforts: </b></span> <span class="remainingEfforts">{{task.pbi.remaining_efforts}}</span></div>
                        <div>
                            <form action="" method="GET">
                                <button style="font-size:12px;border-radius: 5px;border: 0 none; background-color: #bbccdd" class="DeleteButton" name="DeleteButton" value="{{task.id}}">REMOVE</button>
                            </form>
                        </div>
                </div>
                </a>

            </div>
            {%empty%}
            <div>No PBI yet.</div>
            {% endfor %}
        </div>
    </div>

</div>
{% endblock %}

{% block script %}
<script>

        $('.DeleteButton').click(function (e) {
            e.stopPropagation();
        });
        function removePBI(id){
            var confirmation=confirm("Are you sure to remove this PBI?");
            if(confirmation){
                $.ajax({
                    url: "",
                    type: "DELETE",
                    dataType: "json",
                    data: {'task_id': id},
                    async: false,
                    success: function(data){
                        alert("You have removed the PBI "+data.task_id+"from the current sprint backlog!");
                    },
                    error: function () {
                        alert("Something went wrong!");
                    }
                })
            }

        }
        window.onload=function calculate(){
        var remaining_efforts_pbi=document.getElementsByClassName("remainingEfforts");
        var total_efforts_pbi=document.getElementsByClassName("initialEfforts");
        var total_efforts=0;
        var remaining=0;
        for(var i=0;i<remaining_efforts_pbi.length;i++) {
            remaining += parseInt(remaining_efforts_pbi[i].innerText);
            total_efforts+=parseInt(total_efforts_pbi[i].innerText);
        }
        var average=total_efforts/(remaining_efforts_pbi.length);
        var burndown=total_efforts-remaining;
        document.getElementById("totalEf").textContent=total_efforts.toString();
        document.getElementById("remainingEf").textContent=remaining.toString();
        document.getElementById("burndownEf").textContent=burndown.toString();
        document.getElementById("averageEf").textContent=average.toString();

    };
        function createBtnOnclick(){
            document.getElementById("createBtn").style.display = "none";
            document.getElementById("creating").style.display = "block";
        }
    </script>
{% endblock %}

{% block style %}
<style>
    #createBtn{
        margin-top: 255px;
        margin-left: auto;
        margin-right:auto;
        background-color:rgb(148, 73, 63);
        width: 200px;
        padding-top: 10px; 
        padding-left: 10px; 
        font-size: 20px;
        line-height: 20px;
        height: 40px;
        border: 1px solid black;
    }

    .thediv{
        float:left;
        margin:20px;
        width: 600px;
        height: 600px;
    }

    #nav-bar tr td:nth-child(4) {
    background-color: lightblue;
    }

    #SprintInfo{
        margin-left:20px;
        border-radius: 5px;
        background-color: azure;
        /*width:975px;*/
        border: 1px black solid;
    }

    #SprintInfo div{
        margin-left: 30px;
        margin-top: 15px; 
        margin-bottom: 15px;
    }

    .card {
  /* Add shadows to create the "card" effect */
        width:350px;
        height:150px;
        border-radius: 10px;
        margin-left:30px;
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }

    .cardcontainer{
        height: 150px;
    }

    .cardcontainer div{
        float:left;
        font-size: 15px;
        margin:5px;
        height: 20px;
        width:200px;
    }

    .cardcontainer .cardStatus{
        flex: 50%;
        text-align: right;
        float:right;
    }

    .btn{
        font-size:12px;
        border-radius: 5px;
        border: 0 none; 
        background-color: #bbccdd;
    }


</style>
{% endblock %}